deploymentName: pdf-exporter-app
serviceName: pdf-exporter-svc
appLabel: pdf-exporter
dbHost: "host.docker.internal"
profileActive: "macc-prod"
applicationName: "PdfExporterService"
fileDataLocation: /storage/mount/path/data

replicaCount: 1

image:
  repository: docmacc/pdfexporter
  tag: 0.0.1
imagePullPolicy: Always

containerPort: 8007

service:
  port: 80
  targetPort: 8007

volumeMounts:
  mountPath: /storage/mount/path/data

volumeName: persistent-volume-pdf
typeLabel: local
storageClassName: hostpath
capacity:
  storage: 2Gi
accessModes: ReadWriteMany
# Use Docker Desktop specific path formats for 2026
# Windows example: /run/desktop/mnt/host/c/data
# macOS example: /Users/yourname/data
hostPath: /run/desktop/mnt/host/c/Users/Admin/MACCDentalClinicSystem/storage/assets
reclaimPolicy: Retain

volumeClaimName: persistent-volume-pdf-claim
requests:
  storage: 2Gi

environment_enabled: true
configserver_enabled: true
eurekaserver_enabled: true
dbhost_enabled: true
dbport_enabled: false
networkhost_enabled: false
filedatalocation_enabled: true
profile_enabled: true
service_name_enabled: true
volumemounts_enabled: true
volumes_enabled: true
