deploymentName: preprocedures-app
serviceName: preprocedures-svc
appLabel: preprocedures
dbHost: "host.docker.internal"
dbPort: 3307
networkHost: "192.168.0.106"
profileActive: "macc-prod"
applicationName: "PreProcedureService"
fileDataLocation: /storage/mount/path/data/PreProcedure

replicaCount: 1

image:
  repository: docmacc/preprocedure
  tag: 0.0.1
imagePullPolicy: Always

containerPort: 8006

service:
  port: 80
  targetPort: 8006

volumeMounts:
  mountPath: /storage/mount/path/data

volumeName: persistent-volume-preprocedure
typeLabel: local
storageClassName: hostpath
capacity:
  storage: 100Gi
accessModes: ReadWriteMany
# Use Docker Desktop specific path formats for 2026
# Windows example: /run/desktop/mnt/host/c/data
# macOS example: /Users/yourname/data
hostPath: /run/desktop/mnt/host/c/Users/Admin/MACCDentalClinicSystem/storage/assets
reclaimPolicy: Retain

volumeClaimName: persistent-volume-preprocedure-claim
requests:
  storage: 100Gi

environment_enabled: true
configserver_enabled: true
eurekaserver_enabled: true
dbhost_enabled: true
dbport_enabled: true
networkhost_enabled: true
filedatalocation_enabled: true
profile_enabled: true
service_name_enabled: true
volumemounts_enabled: true
volumes_enabled: true
