deploymentName: treatment-plan-app
serviceName: treatment-plan-svc
appLabel: treatment-plan
dbHost: "host.docker.internal"
dbPort: 3307
profileActive: "macc-prod"
applicationName: "TreatmentPlanService"

replicaCount: 1

image:
  repository: kenmac17/treatmentplan
  tag: v1.0.0
imagePullPolicy: Always

containerPort: 8088

service:
  port: 80
  targetPort: 8088

environment_enabled: true
configserver_enabled: true
eurekaserver_enabled: true
dbhost_enabled: true
dbport_enabled: true
networkhost_enabled: false
filedatalocation_enabled: false
profile_enabled: true
service_name_enabled: true
volumemounts_enabled: false
volumes_enabled: false
