deploymentName: intraoral-examination-app
serviceName: intraoral-examination-svc
appLabel: intraoral-examination
dbHost: "host.docker.internal"
dbPort: 3307
profileActive: "desktop-kub-prod"
applicationName: "IntraOralExaminationService"
fileDataLocation: /storage/mount/path/data/IntraoralExamination/DefaultTeeth

replicaCount: 1

image:
  repository: kenmac17/intraoralexamination
  tag: v1.0.0
imagePullPolicy: Always

containerPort: 8085

service:
  port: 80
  targetPort: 8085

volumeMounts:
  mountPath: /storage/mount/path/data

volumeName: persistent-volume-intraoral-examination
typeLabel: local
storageClassName: hostpath
capacity:
  storage: 2Gi
accessModes: ReadWriteMany
# Use Docker Desktop specific path formats for 2026
# Windows example: /run/desktop/mnt/host/c/data
# macOS example: /Users/yourname/data
hostPath: /run/desktop/mnt/host/c/storageMACC
reclaimPolicy: Retain

volumeClaimName: persistent-volume-intraoral-examination-claim
requests:
  storage: 2Gi

environment_enabled: true
configserver_enabled: true
eurekaserver_enabled: true
dbhost_enabled: true
dbport_enabled: true
networkhost_enabled: false
filedatalocation_enabled: true
profile_enabled: true
service_name_enabled: true
volumemounts_enabled: true
volumes_enabled: true
