statefulsetName: eureka
serviceName: eureka-lb
serviceNameNCI: eureka
appLabel: eureka
statefulsetServiceName: "eureka"

replicaCount: 1

image:
  repository: docmacc/serviceregistry
  tag: 0.0.1
imagePullPolicy: Always

containerPort: 8761

service:
  type: NodePort
  port: 80
  targetPort: 8761
